core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views
from .api.views import CartItemViews

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='products'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    # path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),

    path('productlist/list/', views.productList, name='productlist'),
    path('productcreate/create/', views.productCreate, name='productcreate'),
    path('productupdate/<int:id>/', views.update_view, name='productupdate'),
    path('productdelete/<int:id>/', views.delete_view, name='productdelete'),

    path('categorylist/list/', views.categoryList, name='categorylist'),
    path('categorycreate/create/', views.categoryCreate, name='categorycreate'),
    path('categoryupdate/<int:id>/', views.update_category, name='categoryupdate'),
    path('categorydelete/<int:id>/', views.delete_category, name='categorydelete'),

    path('discountlist/list/', views.discountList, name='discountlist'),
    path('discountcreate/create/', views.discountCreate, name='discountcreate'),
    path('discountupdate/<int:id>/', views.update_discount, name='discountupdate'),
    path('discountdelete/<int:id>/', views.delete_discount, name='discountdelete'),
    path('cart/cart-items/', CartItemViews.as_view()),
    path('cart/cart-items/<int:id>', CartItemViews.as_view()),



]

products/forms.py
from django import forms
import datetime
from orders.models import Coupon
from .models import Product, Category


class addProForm(forms.ModelForm):
    # category = forms.ModelMultipleChoiceField(Category, related_name='products')
    # name = forms.CharField(max_length=200)
    # slug = forms.CharField(max_length=200)
    # image = forms.ImageField()
    # description =forms.CharField(widget=forms.Textarea)
    # price = forms.IntegerField()
    available = forms.NullBooleanField()

    class Meta:
        model = Product
        fields = [
            "category",
            "name",
            "slug",
            "price",
            #     "available",
            "image",
            "description",
        ]

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for myField in self.fields:
    #         self.fields[myField].widget.attrs['class'] = 'form-control'


class addCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['is_sub', 'name', 'slug', 'sub_category']


class addDiscountForm(forms.ModelForm):
#     valid_from =  forms.DateField(
#     widget=forms.DateInput(format='%d-%m-%Y %H:%M:%S',attrs={'placeholder':"DD-MM-YY HH:MM:SS"}),
# )
#     valid_to = forms.DateField(
#     widget=forms.DateInput(format='%d-%m-%Y %H:%M:%S',attrs={'placeholder':"DD-MM-YY HH:MM:SS"}),
# )
    class Meta:
        model = Coupon
        fields = ['code','discount','active','valid_from','valid_to']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for myField in self.fields:
    #         self.fields[myField].widget.attrs['class'] = 'form-control'

products/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import status, serializers
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.models import User
from orders.models import OrderItem, Order
from orders.serializer import OrderItemSerializer
from products.models import CartItem, Product
from products.serializer import CartItemSerializer


class CartItemViews(APIView):
    def post(self, request):
        quantity = request.data.get('quantity')
        user_id = request.data.get('user_id')
        products_id = request.data.get('products_id')
        price = request.data.get('price')
        order_id = request.data.get('order_id')
        u = User.objects.get(pk=user_id)
        p = Product.objects.get(pk=products_id)
        print(type(u))
        print(str(p))
        if quantity !='' and user_id !='' and products_id !='' and order_id !='':
            order = Order(user=u)
            Order.save(order)
            item = OrderItem(product=p, order=order, quantity=quantity, price=price)
            OrderItem.save(item)
            print('sjhfosihfewohi')
            return Response('added', status=status.HTTP_200_OK)
        else:
            return Response("error", status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, id=None):
        if id:
            item = OrderItem.objects.get(id=id)
            serializer = OrderItemSerializer(item)
            return Response({"data": serializer.data}, status=status.HTTP_200_OK)

        items = OrderItem.objects.all()
        serializer = OrderItemSerializer(items, many=True)
        return Response({"data": serializer.data}, status=status.HTTP_200_OK)

    def patch(self, request, id=None):
        quantity = request.data.get('quantity')
        user_id = request.data.get('user_id')
        products_id = request.data.get('products_id')
        price = request.data.get('price')

        if quantity !='' or user_id !='' or products_id !='':
            item = Order.objects.get(id=id)
            item.user_id = user_id
            Order.save(item)
            order_item = OrderItem.objects.get(order_id=item.id)
            order_item.price = price
            order_item.quantity = quantity
            order_item.product_id = products_id
            OrderItem.save(order_item)
            return Response('update')
        else:
            return Response('error')

    def delete(self, request, id=None):
        # id = request.data.get('order_id')
        o = Order.objects.get(pk=id)
        print(str(o))
        o.delete()
        return Response({"data": "Item Deleted"})




#  "data": {
#         "products_id": "1",
#
#         "price": 530,
#         "quantity": 4,
#         "user_id": "1",
#
#     }


@api_view(['POST'])
def update_items(request, pk):
    item = CartItem.objects.get(pk=pk)
    data = CartItemSerializer(instance=item, data=request.data)

    if data.is_valid():
        data.save()
        return Response(data.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)

products/views.py
# from . import tasks
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

# from utils import IsAdminUserMixin
from rest_framework import serializers, status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from orders.cart import Cart
from orders.forms import CartAddForm
from orders.models import Coupon, Order
from .forms import addProForm, addCategoryForm, addDiscountForm
from .models import Product, Category, CartItem
from .serializer import CartItemSerializer


class HomeView(View):
    def get(self, request, category_slug=None):
        cart = Cart(request)
        print()
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'home/home.html', {'products': products, 'categories': categories, 'cart': len(cart)})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)

        if product.discount is not None:
            x = product.discount * 0.01
            y = product.price * x
            z = product.price - (y)
            product.price = z
            print(product.price)
        form = CartAddForm()
        return render(request, 'home/detail.html', {'product': product, 'form': form})


class IsAdminUserMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_admin


# class BucketHome(IsAdminUserMixin, View):
#     template_name = 'home/bucket.html'
#
#     def get(self, request):
#         # objects = tasks.all_bucket_objects_task()
#         return render(request, self.template_name)
#
#
# class DeleteBucketObject(IsAdminUserMixin, View):
#     def get(self, request, key):
#         # tasks.delete_object_task.delay(key)
#         messages.success(request, 'your object will be delete soon.', 'info')
#         return redirect('home:bucket')
#
#
# class DownloadBucketObject(IsAdminUserMixin, View):
#     def get(self, request, key):
#         # tasks.download_object_task.delay(key)
#         messages.success(request, 'your download will start soon.', 'info')
#         return redirect('home:bucket')
class my_form(View):
    def get(self, request):
        return render(request, 'home/addProduct.html', )

    def post(self, request):
        form = addProForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = addProForm()
            return render(request, 'home/addProduct.html', {'form': form})


def productList(request):
    # print(id)
    products = Product.objects.all()
    return render(request, "home/product-list.html", {'products': products})


def categoryList(request):
    # print(id)
    category = Category.objects.all()
    return render(request, "home/category-list.html", {'category': category})


def discountList(request):
    # print(id)
    discount = Coupon.objects.all()
    return render(request, "home/discount-list.html", {'discount': discount})


def productCreate(request):
    if request.method == "POST":
        form = addProForm(request.POST, request.FILES)

        try:
            print("igriutirutury")

            if form.is_valid():
                try:
                    model = form.instance
                    form.save(model)
                    return redirect('products:productlist')
                except:
                    pass
        except Exception as e:
            # raise Exception as e:
            print(e)
    else:
        form = addProForm()
    return render(request, 'home/product-create.html', {'form': form})


def categoryCreate(request):
    if request.method == "POST":
        form = addCategoryForm(request.POST)
        print('cateeeee')
        try:
            print("igriutirutury")

            if form.is_valid():
                try:
                    model = form.instance
                    form.save(model)
                    return redirect('products:categorylist')
                except:
                    pass
        except Exception as e:
            # raise Exception as e:
            print(e)
    else:
        form = addCategoryForm()
    return render(request, 'home/category-create.html', {'form': form})


def discountCreate(request):
    if request.method == "POST":
        form = addDiscountForm(request.POST)
        print('cateeeee')
        try:
            print("igriutirutury")

            if form.is_valid():
                try:
                    model = form.instance
                    print("utourotureit")
                    form.save(model)
                    print("hjdfjhdhfshdj")
                    return redirect('products:discountlist')
                except:
                    pass
        except Exception as e:
            # raise Exception as e:
            print(e)
    else:
        form = addDiscountForm()
    return render(request, 'home/discount-create.html', {'form': form})


def create_view(request):
    context = {}
    form = addProForm(request.POST or None)
    if form.is_valid():
        form.save()
        print('saaasasasaaaaaaaaaaaaa')
    else:
        print("jjjjjjjjjj")
    context['form'] = form
    return render(request, "home/product-create.html", context)


def productUpdate(request, id):
    product = Product.objects.get(id=id)
    form = addProForm(initial={'category': product.category,
                               'name': product.name,
                               'image': product.image,
                               'description': product.description,
                               'price': product.price,
                               })
    if request.method == "POST":
        form = addProForm(request.POST, instance=product)
        if form.is_valid():
            try:
                model = form.instance
                form.save(model)
                return redirect('productlist/list/')
            except Exception as e:
                print(e)
    return render(request, 'home/product-update.html', {'form': form})


def delete_view(request, id):
    context = {}
    obj = get_object_or_404(Product, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect("products:productlist")

    return render(request, "home/delete_view.html", context)


def delete_category(request, id):
    context = {}
    obj = get_object_or_404(Category, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect("products:categorylist")

    return render(request, "home/delete_category.html", context)
def delete_discount(request, id):
    context = {}
    obj = get_object_or_404(Coupon, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect("products:discountlist")

    return render(request, "home/delete_discount.html", context)


def update_view(request, id):
    context = {}
    obj = get_object_or_404(Product, id=id)
    form = addProForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('products:productlist')
    context["form"] = form
    return render(request, "home/product-update.html", context)


def update_category(request, id):
    context = {}
    obj = get_object_or_404(Category, id=id)
    form = addCategoryForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('products:categorylist')
    context["form"] = form
    return render(request, "home/category-update.html", context)


def update_discount(request, id):
    context = {}
    obj = get_object_or_404(Coupon, id=id)
    form = addDiscountForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('products:discountlist')
    context["form"] = form
    return render(request, "home/discount-update.html", context)



@api_view(['POST'])
def add_items(request):
    item = CartItemSerializer(data=request.data)

    # validating for already existing data
    if CartItem.objects.filter(**request.data).exists():
        raise serializers.ValidationError('This data already exists')

    if item.is_valid():
        item.save()
        return Response(item.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)


@api_view(['GET'])
def view_items(request):
    # checking for the parameters from the URL
    if request.query_params:
        items = CartItem.objects.filter(**request.query_params.dict())
    else:
        items = CartItem.objects.all()

    # if there is something in items else raise error
    if items:
        serializer = CartItemSerializer(items, many=True)
        return Response(serializer.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)


@api_view(['POST'])
def update_items(request, pk):
    item = CartItem.objects.get(pk=pk)
    data = CartItemSerializer(instance=item, data=request.data)

    if data.is_valid():
        data.save()
        return Response(data.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)
# @api_view(['DELETE'])
# def delete_items(request, pk):
#     item = get_object_or_404(Order, pk=pk)
#     item.delete()
#     return Response(status=status.HTTP_202_ACCEPTED)

products/templates/home/category-create.html
{#<!DOCTYPE html>#}
{#{% extends 'base.html' %}#}
{#{% load static %}#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="container">#}
{#    <form method="POST" action="{% url 'products:addProduct' %}">#}
{#      <fieldset>#}
{#        <legend>Form</legend>#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="btn btn-primary">Submit</button>#}
{#      </fieldset>#}
{#    </form>#}
{#</div>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">#}
{#<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
{#<div class="container">#}
{#<form method="post" action="{% url 'products:addProduct' %}">#}
{#      {% csrf_token %}#}
{#  <div class="form-row">#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputEmail4">Email</label>#}
{#      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">#}
{#    </div>#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputPassword4">Password</label>#}
{#      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <label for="inputAddress">Address</label>#}
{#    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <label for="inputAddress2">Address 2</label>#}
{#    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">#}
{#  </div>#}
{#  <div class="form-row">#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputCity">City</label>#}
{#      <input type="text" class="form-control" id="inputCity">#}
{#    </div>#}
{#    <div class="form-group col-md-4">#}
{#      <label for="inputState">State</label>#}
{#      <select id="inputState" class="form-control">#}
{#        <option selected>Choose...</option>#}
{#        <option>...</option>#}
{#      </select>#}
{#    </div>#}
{#    <div class="form-group col-md-2">#}
{#      <label for="inputZip">Zip</label>#}
{#      <input type="text" class="form-control" id="inputZip">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <div class="form-check">#}
{#      <input class="form-check-input" type="checkbox" id="gridCheck">#}
{#      <label class="form-check-label" for="gridCheck">#}
{#        Check me out#}
{#      </label>#}
{#    </div>#}
{#  </div>#}
{#  <button type="submit" class="btn btn-primary">Sign in</button>#}
{#</form>#}
{#</div>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>#}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>#}
{#</body>#}
{#</html>#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<form method="POST" enctype="multipart/form-data">#}
{##}
{#    <!-- Security token -->#}
{#    {% csrf_token %}#}
{##}
{#    <!-- Using the formset -->#}
{#    {{ form.as_p }}#}
{##}
{#    <input type="submit" value="Submit">#}
{#</form>#}
{##}
{##}
{#</body>#}
{#</html>#}
{##}
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h5>Create New category</h5>
    <form method="POST" >
        {% csrf_token %}
        {{form.as_p}}
{#        <a type="button" class="btn btn-danger">Cancel</a>#}
{#        <button type="submit" class="btn btn-success">Create</button>#}
{#        <input type="submit" value="Submit" class="btn btn-success">#}
        <input type="submit" value="Submit" class="btn  btn-success"  href="{% url 'products:categorycreate' %}">
        <a type="button" class="btn btn-danger" href="{% url 'products:categorylist' %}">cancle</a>
    </form>
</div>
{% endblock %}

products/templates/home/category-list.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="main">#}
{##}
{#    {% for data in dataset %}.#}
{##}
{#    {{ data.name }}<br/>#}
{#    {{ data.price }}<br/>#}
{#    {{ data.category }}<br/>#}
{##}
{#    <hr/>#}
{##}
{#    {% endfor %}#}
{##}
{#</div>#}
{#</body>#}
{#</html>#}

{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>category List</h4>
    <table class="table">
        <thead>
            <tr>
{#                <th scope="col">category</th>#}
                <th scope="col">name</th>
{#                <th scope="col">Slug</th>#}
{#                <th scope="col">image</th>#}
{#                <th scope="col">description</th>#}
{#                <th scope="col">price</th>#}
{#                <th scope="col">available</th>#}
            </tr>
        </thead>
        <tbody>
            {% for cat in category %}
            <tr>
{#                <td>{{ product.category.name }}</td>#}
                <td>{{ cat.name }}</td>
{#                <td>{{ product.Slug }}</td>#}
{#                <td>{{ product.description }}</td>#}
{#                <td>{{ product.price }}</td>#}
{#                <td>{{ product.available }}</td>#}
{#                <td><a type="button" class="btn btn-warning" href="{% url 'products:categoryupdate' cat.id %}">Update</a>#}
                <td><a type="button" class="btn btn-warning" href="/categoryupdate/{{ cat.id }}">Update</a>
                    <a type="button" class="btn btn-danger" href="/categorydelete/{{ cat.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a type="button" class="btn btn-success" href="{% url 'products:categorycreate' %}">Create</a>
</div>
{% endblock %}

products/templates/home/discount-create.html
{#<!DOCTYPE html>#}
{#{% extends 'base.html' %}#}
{#{% load static %}#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="container">#}
{#    <form method="POST" action="{% url 'products:addProduct' %}">#}
{#      <fieldset>#}
{#        <legend>Form</legend>#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="btn btn-primary">Submit</button>#}
{#      </fieldset>#}
{#    </form>#}
{#</div>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">#}
{#<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
{#<div class="container">#}
{#<form method="post" action="{% url 'products:addProduct' %}">#}
{#      {% csrf_token %}#}
{#  <div class="form-row">#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputEmail4">Email</label>#}
{#      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">#}
{#    </div>#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputPassword4">Password</label>#}
{#      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <label for="inputAddress">Address</label>#}
{#    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <label for="inputAddress2">Address 2</label>#}
{#    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">#}
{#  </div>#}
{#  <div class="form-row">#}
{#    <div class="form-group col-md-6">#}
{#      <label for="inputCity">City</label>#}
{#      <input type="text" class="form-control" id="inputCity">#}
{#    </div>#}
{#    <div class="form-group col-md-4">#}
{#      <label for="inputState">State</label>#}
{#      <select id="inputState" class="form-control">#}
{#        <option selected>Choose...</option>#}
{#        <option>...</option>#}
{#      </select>#}
{#    </div>#}
{#    <div class="form-group col-md-2">#}
{#      <label for="inputZip">Zip</label>#}
{#      <input type="text" class="form-control" id="inputZip">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <div class="form-check">#}
{#      <input class="form-check-input" type="checkbox" id="gridCheck">#}
{#      <label class="form-check-label" for="gridCheck">#}
{#        Check me out#}
{#      </label>#}
{#    </div>#}
{#  </div>#}
{#  <button type="submit" class="btn btn-primary">Sign in</button>#}
{#</form>#}
{#</div>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>#}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>#}
{#</body>#}
{#</html>#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<form method="POST" enctype="multipart/form-data">#}
{##}
{#    <!-- Security token -->#}
{#    {% csrf_token %}#}
{##}
{#    <!-- Using the formset -->#}
{#    {{ form.as_p }}#}
{##}
{#    <input type="submit" value="Submit">#}
{#</form>#}
{##}
{##}
{#</body>#}
{#</html>#}
{##}
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h5>Create New discount</h5>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
{#        <a type="button" class="btn btn-danger">Cancel</a>#}
{#        <button type="submit" class="btn btn-success">Create</button>#}
{#        <input type="submit" value="Submit" class="btn btn-success">#}
        <input type="submit" value="Submit" class="btn  btn-success"  href="{% url 'products:discountcreate' %}">
        <a type="button" class="btn btn-danger" href="{% url 'products:discountlist' %}">cancle</a>
    </form>
</div>
{% endblock %}