accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('loginapi/', views.loginView.as_view(), name='user_login_api'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

    path('addresslist/list/', views.addressList, name='addresslist'),
    path('addressListManagement/list/', views.addressListManagement, name='addressListManagement'),
    path('addresscreate/create/', views.addressCreate, name='addresscreate'),
    path('addressupdate/<int:id>/', views.update_address, name='addressupdate'),
    path('addressdelete/<int:id>/', views.delete_address, name='addressdelete'),
    path('profileUpdate/', views.profileUpdate, name='profileUpdate'),
    path('nazer_panel/', views.nazer_panel, name='nazer_panel'),
    path('usercreate/', views.Operator_user_create, name='usercreate'),
    path('userlist/', views.operator_user_List, name='userlist'),
    path('userupdate/<int:id>/', views.update_Operator_user_, name='userupdate'),
    path('userdelete/<int:id>/', views.delete_user_operator, name='userdelete'),
    path('customer/addAddress', views.customerAddAddress, name='cusAdd'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
    path('', views.OrderView.as_view(), name='OrderView'),  # endpoint
    path('all/', views.showAllOrders),
    path('allOrderItem/', views.showAllOrderItems),
    path('orderView/<int:pk>/', views.show),
    path('orderItemView/<int:pk>/', views.showOrderItemView),
    path('orderHistoryList/history/', views.orderHistoryList,name='orderHistoryList'),
    path('orderStatusList/status/', views.orderStatusList,name='orderHistoryStatusList'),
    path('order_List/list/', views.order_List,name='order_List'),
    path('orderItemcreate/', views.orderItemcreate,name='orderItemcreate'),
    path('orderItemDelete/<int:id>/', views.orderItemDelete,name='orderItemDelete'),
    path('orderItemUpdate/<int:id>/', views.orderItemUpdate,name='orderItemUpdate'),
    # path('getAllProduct/test/', views.getAllProduct,name='getAllProduct'),
]

products/urls.py
from django.urls import path

from . import views
from .api.views import CartItemViews

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='products'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    # path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),

    path('productlist/list/', views.productList, name='productlist'),
    path('productcreate/create/', views.productCreate, name='productcreate'),
    path('productupdate/<int:id>/', views.update_view, name='productupdate'),
    path('productdelete/<int:id>/', views.delete_view, name='productdelete'),

    path('categorylist/list/', views.categoryList, name='categorylist'),
    path('categorycreate/create/', views.categoryCreate, name='categorycreate'),
    path('categoryupdate/<int:id>/', views.update_category, name='categoryupdate'),
    path('categorydelete/<int:id>/', views.delete_category, name='categorydelete'),

    path('discountlist/list/', views.discountList, name='discountlist'),
    path('discountcreate/create/', views.discountCreate, name='discountcreate'),
    path('discountupdate/<int:id>/', views.update_discount, name='discountupdate'),
    path('discountdelete/<int:id>/', views.delete_discount, name='discountdelete'),
    path('cart/cart-items/', CartItemViews.as_view()),
    path('cart/cart-items/<int:id>', CartItemViews.as_view()),



]

orders/models.py
# from django.db import models
#
# from products.models import Products
# from accounts.models import User
#
#
# class Orders(models.Model):
#     count = models.IntegerField(null=False)
#     # sum_price = models.CharField(max_length=10, null=False)
#     product =  models.ForeignKey(Products, verbose_name='pro_id', related_name='pro_id',
#                                  on_delete=models.CASCADE, null=True)
#     customer = models.ForeignKey(User, verbose_name='cus_id', related_name='cus_id',
#                                  on_delete=models.CASCADE, null=True)
#
#     class Meta:
#         verbose_name = 'ordes'
#
#     def __str__(self):
#         return self.product.name + ":" + str(self.count)

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=None)
    sent_status=models.BooleanField(default=False)
    # totalprice
    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

orders/forms.py
from ckeditor.fields import RichTextField
from django import forms

from orders.models import OrderItem
from products.models import Category


class CartAddForm(forms.Form):
	quantity = forms.IntegerField(min_value=1, max_value=9)


class CouponApplyForm(forms.Form):
	code = forms.CharField()

class orderItemForm(forms.ModelForm):
	class Meta:
		model = OrderItem
		fields='__all__'

orders/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.models import Address
from .cart import Cart
from .forms import CartAddForm, CouponApplyForm, orderItemForm
from .models import Order, OrderItem, Coupon
from .models import Product
from .serializer import OrderSerializer, OrderItemSerializer


# import requests

class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(View):
    # todo kkkkkkkkkkkkk

    print('permision_required')

    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


# @api_view
class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderDetailView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        id = request.user.id
        address = Address.objects.filter(customer_id=id)
        return render(request, 'orders/order.html', {'order': order, 'form': self.form_class, 'address': address})


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        return redirect('orders:order_detail', order.id)


class OrderPayView(LoginRequiredMixin, View):
    # permission_required = 'orders.add_order'
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        request.session['order_pay'] = {
            'order_id': order.id,
        }
        order.paid = True
        order.sent_status = True
        order.save()
        return redirect('/')


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = Order.objects.get(id=int(order_id))
        # t_status = request.GET.get('Status')
        # t_authority = request.GET['Authority']
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json",
                          "content-type": "application/json'"}

        else:
            return HttpResponse('Transaction failed or canceled by user')


class CouponApplyView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def post(self, request, order_id):
        now = datetime.datetime.now()
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'this coupon does not exists', 'danger')
                return redirect('orders:order_detail', order_id)
            order = Order.objects.get(id=order_id)
            order.discount = coupon.discount
            order.save()
        return redirect('orders:order_detail', order_id)


# -----------------
class OrderView(APIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request):
        persons = Order.objects.all()
        ser_data = OrderSerializer(instance=persons, many=True)
        return Response(data=ser_data.data)


# class OrderItemListView(APIView):
#     throttle_scope = 'orderItem'
#
#     def get(self, request):
#         questions = OrderItem.objects.all()
#         srz_data = OrderItemSerializer(instance=questions, many=True).data
#         return Response(srz_data, status=status.HTTP_200_OK)

@api_view()
def showAllOrders(request):
    home = Order.objects.all()
    serializer = OrderSerializer(instance=home, many=True)
    return Response(data=serializer.data)


@api_view(['GET', 'PUT', 'DELETE'])
def show(request, pk):
    home = Order.objects.all()
    serializer = OrderSerializer(instance=home, many=True)
    # return Response(data=serializer.data)

    try:
        snippet = Order.objects.get(pk=pk)
    except Order.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = OrderSerializer(snippet)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = OrderSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view()
def showAllOrderItems(request):
    home = OrderItem.objects.all()
    serializer = OrderItemSerializer(instance=home, many=True)
    return Response(data=serializer.data)


@api_view(['GET', 'PUT', 'DELETE'])
def showOrderItemView(request, pk):
    home = OrderItem.objects.all()
    serializer = OrderSerializer(instance=home, many=True)
    # return Response(data=serializer.data)

    try:
        snippet = OrderItem.objects.get(pk=pk)
    except Order.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = OrderItemSerializer(snippet)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = OrderItemSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


    # class OrderItemCreateView(APIView):
    #     """
    #         Create a new question
    #     """
    #     permission_classes = [IsAuthenticated, ]
    #     serializer_class = OrderItemSerializer
    #
    #     def post(self, request):
    #         srz_data = OrderItemSerializer(data=request.data)
    #         if srz_data.is_valid():
    #             srz_data.save()
    #             return Response(srz_data.data, status=status.HTTP_201_CREATED)
    #         return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)
    #
    #
    # class QuestionUpdateView(APIView):
    #     permission_classes = [IsOwnerOrReadOnly, ]
    #
    #     def put(self, request, pk):
    #         question = OrderItem.objects.get(pk=pk)
    #         self.check_object_permissions(request, question)
    #         srz_data = OrderItem(instance=question, data=request.data, partial=True)
    #         if srz_data.is_valid():
    #             srz_data.save()
    #             return Response(srz_data.data, status=status.HTTP_200_OK)
    #         return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)
    #
    #
    # class QuestionDeleteView(APIView):
    #     permission_classes = [IsOwnerOrReadOnly, ]
    #
    #     def delete(self, request, pk):
    #         question = OrderItem.objects.get(pk=pk)
    #         question.delete()
    #         return Response({'message': ' deleted'}, status=status.HTTP_200_OK)
    # class OrderList(mixins.RetrieveModelMixin,
    #                     mixins.UpdateModelMixin,
    #                     mixins.DestroyModelMixin,
    #                     generics.GenericAPIView):
    #     """
    #     List all orders, or create a new snippet.
    #     """
    #     # serializer_class = OrganisationDetailSerializer
    #     queryset = Order.objects.all()
    #     serializer_class = OrderSerializer
    #     lookup_field = 'orderview'
    #
    #
    #     def get(self, request, *args, **kwargs):
    #         return self.retrieve(request, *args, **kwargs)
    #
    #     def put(self, request, *args, **kwargs):
    #         return self.update(request, *args, **kwargs)
    #
    #     def delete(self, request, *args, **kwargs):
    #         return self.destroy(request, *args, **kwargs)
    #     # def get_object(self, pk):
    #     #     try:
    #     #         return Order.objects.get(pk=pk)
    #     #     except Order.DoesNotExist:
    #     #         raise Http404
    #     #
    #     # def get(self, request, pk, format=None):
    #     #     snippet = self.get_object(pk)
    #     #     serializer = OrderSerializer(snippet)
    #     #     return Response(serializer.data)
    #     #
    #     # def put(self, request, pk, format=None):
    #     #     snippet = self.get_object(pk)
    #     #     serializer = OrderSerializer(snippet, data=request.data)
    #     #     if serializer.is_valid():
    #     #         serializer.save()
    #     #         return Response(serializer.data)
    #     #     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    #     #
    #     # def delete(self, request, pk, format=None):
    #     #     snippet = self.get_object(pk)
    #     #     snippet.delete()
    #     #     return Response(status=status.HTTP_204_NO_CONTENT)

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
{#    {{ cart.lenght}}#}
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'orders:cart_remove' item.product.id %}">remove</a></td>
    </tr>
    {% endfor %}

    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>

    </tbody>
</table>

<a href="{% url 'orders:order_create' %}" class="btn btn-primary">continue</a>
{#<a href="{% url 'products:products' %}" class="btn btn-warning">back</a>#}

{% endblock %}

orders/templates/orders/create-order.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h5>Create New order</h5>
    <form method="POST" >
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Submit" class="btn  btn-success"  href="{% url 'orders:orderItemcreate' %}">
        <a type="button" class="btn btn-danger" href="{% url 'orders:order_List' %}">cancle</a>
    </form>
</div>
{% endblock %}

orders/templates/orders/delete_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="{% url 'orders:order_List' %}">Cancel </a>
    </form>
</div>
</body>
</html>

orders/templates/orders/order-list.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="main">#}

{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>order List</h4>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">user</th>
                <th scope="col">paid</th>
                <th scope="col">sent_status</th>
                <th scope="col">product name</th>
                <th scope="col">price</th>
{#                <th scope="col">quantity</th>#}
{#                <th scope="col">available</th>#}
            </tr>
        </thead>
        <tbody>
            {% for dis in order %}
            <tr>
                <td>{{ dis.order.user.full_name }}</td>
                <td>{{ dis.order.paid }}</td>
                <td>{{ dis.order.sent_status }}</td>
                <td>{{ dis.product.name }}</td>
                <td>{{ dis.product.price }}</td>
{#                <td>{{ dis.product.quantity }}</td>#}

{#                <td>{{ dis.active }}</td>#}
{#                <a href="{% url 'home:download_obj_bucket' obj.Key %}">download</a></td>#}
                <td><a type="button" class="btn btn-warning" href="/orders/orderItemUpdate/{{ dis.id }} ">Update</a>
                    <a type="button" class="btn btn-danger" href="/orders/orderItemDelete/{{ dis.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a type="button" class="btn btn-success" href="{% url 'orders:orderItemcreate' %}">Create</a>
</div>
{% endblock %}

orders/templates/orders/order-update.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>Update order</h4>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <a type="button" class="btn btn-danger" href="{% url 'orders:order_List' %}">Cancel</a>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{#{% extends 'paypage.html' %}#}

{% load static %}
{% block content %}

    <section class=" " style=" margin: 45px 0; height: 350px;
    position: relative;">
        <div class="container">
            <div class="row" style="">
                <div class="col-lg-6"
                     style="background-color: #f5d3d3;box-shadow: 2px 2px 6px 2px rgba(0, 0, 0, 0.23);">
                    <div>


                        <br/>

                        <div style="width: 90%">
                            {#                            <p>select address</p>#}
                            <img src="{% static 'js/add.jpeg' %}" width="60px">
                            <a type="button"  class="btn  btn-success"
                               href="{% url 'accounts:cusAdd' %}">add address</a>

                            <select class="form-select" aria-label="Default select example">
                                <option selected>Open this select address</option>
                                {% for add in address %}
                                    <option value="1">city_name:{{ add.city_name }} , avenue_name:{{ add.avenue_name }}
                                        ,
                                        street_name:{{ add.street_name }} ,
                                        plate:{{ add.plate }} , zipcode:{{ add.zipCode }}</option>
                                {% endfor %}
                            </select>

                        </div>

                        <br/>
                        <br/>
                        <div style="text-align:center;margin-top:10%">
                            <p>COUPON CODE</p>
                            <form action="{% url 'orders:apply_coupon' order.id %}" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" class="btn btn-primary" value="Apply">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login_form_inner">

                        <div class="row">
                            <aside class="col-sm-12">
                                <article class="card">
                                    <div class="card-body p-5">
                                        <form role="form">
                                            <div class="form-group">
                                                <label for="username">Full name (on the card)</label>
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                            <span class="input-group-text"><i
                                                                    class="bi bi-person"></i></span>
                                                    </div>
                                                    <input type="text" class="form-control" name="username"
                                                           placeholder="" required="">
                                                </div> <!-- input-group.// -->
                                            </div> <!-- form-group.// -->

                                            <div class="form-group">
                                                <label for="cardNumber">Card number</label>
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                            <span class="input-group-text"><i
                                                                    class="bi bi-credit-card"></i></span>
                                                    </div>
                                                    <input type="text" class="form-control" name="cardNumber"
                                                           placeholder="">
                                                </div> <!-- input-group.// -->
                                            </div> <!-- form-group.// -->

                                            <div class="row">
                                                <div class="col-sm-8">
                                                    <div class="form-group">
                                                        <label><span class="hidden-xs">Expiration</span> </label>
                                                        <div class="form-inline">
                                                            <select class="form-control" style="width:45%">
                                                                <option>MM</option>
                                                                <option>01 - Janiary</option>
                                                                <option>02 - February</option>
                                                                <option>03 - February</option>
                                                            </select>
                                                            <span style="width:10%; text-align: center"> / </span>
                                                            <select class="form-control" style="width:45%">
                                                                <option>YY</option>
                                                                <option>2018</option>
                                                                <option>2019</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        <label data-toggle="tooltip" title=""
                                                               data-original-title="3 digits code on back side of the card">CVV
                                                            <i class="fa fa-question-circle"></i></label>
                                                        <input class="form-control" required="" type="text">
                                                    </div> <!-- form-group.// -->
                                                </div>
                                            </div> <!-- row.// -->
                                            <p>Total: {{ order.get_total_price }}</p>
                                            <a href="{% url 'orders:order_pay' order.id %}" class="btn btn-primary"
                                               style="margin-left: 45%">Pay</a>
                                        </form>
                                    </div> <!-- card-body.// -->
                                </article> <!-- card.// -->


                            </aside> <!-- col.// -->

                        </div> <!-- row.// -->
                    </div>
                </div>
            </div>
        </div>

    </section>


















{% endblock %}