accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('loginapi/', views.loginView.as_view(), name='user_login_api'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

    path('addresslist/list/', views.addressList, name='addresslist'),
    path('addressListManagement/list/', views.addressListManagement, name='addressListManagement'),
    path('addresscreate/create/', views.addressCreate, name='addresscreate'),
    path('addressupdate/<int:id>/', views.update_address, name='addressupdate'),
    path('addressdelete/<int:id>/', views.delete_address, name='addressdelete'),
    path('profileUpdate/', views.profileUpdate, name='profileUpdate'),
    path('nazer_panel/', views.nazer_panel, name='nazer_panel'),
    path('usercreate/', views.Operator_user_create, name='usercreate'),
    path('userlist/', views.operator_user_List, name='userlist'),
    path('userupdate/<int:id>/', views.update_Operator_user_, name='userupdate'),
    path('userdelete/<int:id>/', views.delete_user_operator, name='userdelete'),
    path('customer/addAddress', views.customerAddAddress, name='cusAdd'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views
from .api.views import CartItemViews

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='products'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    # path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),

    path('productlist/list/', views.productList, name='productlist'),
    path('productcreate/create/', views.productCreate, name='productcreate'),
    path('productupdate/<int:id>/', views.update_view, name='productupdate'),
    path('productdelete/<int:id>/', views.delete_view, name='productdelete'),

    path('categorylist/list/', views.categoryList, name='categorylist'),
    path('categorycreate/create/', views.categoryCreate, name='categorycreate'),
    path('categoryupdate/<int:id>/', views.update_category, name='categoryupdate'),
    path('categorydelete/<int:id>/', views.delete_category, name='categorydelete'),

    path('discountlist/list/', views.discountList, name='discountlist'),
    path('discountcreate/create/', views.discountCreate, name='discountcreate'),
    path('discountupdate/<int:id>/', views.update_discount, name='discountupdate'),
    path('discountdelete/<int:id>/', views.delete_discount, name='discountdelete'),
    path('cart/cart-items/', CartItemViews.as_view()),
    path('cart/cart-items/<int:id>', CartItemViews.as_view()),



]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.core.validators import RegexValidator
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, phone_number, email, full_name, password):
        if not phone_number:
            raise ValueError('user must have phone number')

        if not email:
            raise ValueError('user must have email')

        if not full_name:
            raise ValueError('user must have full name')

        user = self.model(phone_number=phone_number, email=self.normalize_email(email), full_name=full_name)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, email, full_name, password):
        user = self.create_user(phone_number, email, full_name, password)
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    #
    def create_customer(self, phone_number, email, full_name, password):
        user = self.create_user(phone_number, email, full_name, password)
        user.is_customer = True
        user.save(using=self._db)
        return user

    #
    def create_operator(self, phone_number, email, full_name, password):
        user = self.create_user(phone_number, email, full_name, password)
        user.is_operator = True
        user.save(using=self._db)
        return user

    def create_nazer(self, phone_number, email, full_name, password):
        user = self.create_user(phone_number, email, full_name, password)
        user.is_nazer = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    roles = [
        ('customer', 'customer'),
        ('nazer', 'nazer'),
        ('operator', 'operator'),
        ('admin', 'admin'),
    ]
    email = models.EmailField(max_length=255, unique=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$',
                                 message="Phone number must be entered in the format: '+919198989'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=11, blank=True, unique=True)
    national_code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_nazer = models.BooleanField(default=False)
    is_operator = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    role = models.CharField(choices=roles, max_length=15, null=True, blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin

    # def is_customer(self):
    #     return self.is_customer
    #
    # def is_operator(self):
    #     return self.is_operator
    #
    # def is_nazer(self):
    #     return self.is_nazer

    # @is_nazer.setter
    # def is_nazer(self, value):
    #     self._is_nazer = value
    #
    # @is_operator.setter
    # def is_operator(self, value):
    #     self._is_operator = value
    #
    # @is_customer.setter
    # def is_customer(self, value):
    #     self._is_customer = value


class Address(models.Model):
    city_name = models.CharField(max_length=50, null=False)
    avenue_name = models.CharField(max_length=50, null=False)
    street_name = models.CharField(max_length=50, null=False)
    plate = models.CharField(max_length=3, null=False)
    zipCode = models.CharField(max_length=10, null=False)
    customer = models.ForeignKey(User, verbose_name='customer_id', related_name='customer_id',
                                 on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.city_name + ":" + self.avenue_name + ":" + \
               self.zipCode + ":" + self.plate

accounts/views.py
import random

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View, csrf
from rest_framework import status, views, permissions
from rest_framework.decorators import api_view
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from orders.cart import Cart, CART_SESSION_ID
from orders.forms import CartAddForm
from orders.models import Order, Coupon
from products.models import Product, Category
from .forms import UserRegistrationForm, VerifyCodeForm, UserLoginForm, addAddressForm, updateUserForm, \
    User_RegistrationForm
from .models import User, Address
from .serializer import UserSerializer


class UserRegisterView(View):
    # todo is addmin or just customer
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            # send_otp_code(form.cleaned_data['phone'], random_code)
            # OtpCode.objects.create(phone_number=form.cleaned_data['phone'], code=random_code)
            request.session['user_registration_info'] = {
                'phone_number': form.cleaned_data['phone'],
                'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'password': form.cleaned_data['password'],
            }
            user_session = request.session['user_registration_info']
            User.objects.create_customer(user_session['phone_number'], user_session['email'], user_session['full_name'],
                                     user_session['password'])
            messages.success(request, 'you registered.', 'success')
            # messages.success(request, 'we sent you a code', 'success')
            # return redirect('products:home')
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/verify.html', {'form': form})


# def post(self, request):
# 	user_session = request.session['user_registration_info']
# 	code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
# 	form = self.form_class(request.POST)
# 	if form.is_valid():
# 		cd = form.cleaned_data
# 		if cd['code'] == code_instance.code:
# 			User.objects.create_user(user_session['phone_number'], user_session['email'],
# 									 user_session['full_name'], user_session['password'])
#
# 			code_instance.delete()
# 			messages.success(request, 'you registered.', 'success')
# 			return redirect('home:home')
# 		else:
# 			messages.error(request, 'this code is wrong', 'danger')
# 			return redirect('accounts:verify_code')
# 	return redirect('home:home')


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('products:products')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        print(str(request.session.session_key))
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        key = request.session
        print(str(request.session.get(CART_SESSION_ID)) + "---")

        # cart = copy.deepcopy(Cart(request).cart)
        # logout(request)
        # session = request.session
        # session[CART_SESSION_ID] = cart
        # session.modified = True
        # todo

        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # request.session.session_key=key
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            # print('authenticate' + request.session.session_key)

            if user is not None:
                # print('before login' + request.session.session_key)
                # print('before login'+str(cart.Cart))

                login(request, user)
                # url=request.get('next')
                # settp
                cart = Cart(request)
                product = get_object_or_404(Product, id=1)
                form = CartAddForm(request.POST)
                if form.is_valid():
                    cart.add(product, form.cleaned_data['quantity'])
                messages.success(request, 'you logged in successfully', 'info')
                if str(request.session.get(CART_SESSION_ID))=='{}':
                    return redirect('products:products')

                else:
                    return redirect('orders:cart')


            messages.error(request, 'phone or password is wrong', 'warning')
        return render(request, self.template_name, {'form': form})


def addressList(request):
    id = request.user.id
    print(id)
    address = Address.objects.filter(customer_id=id)
    # address = Address.objects.get(Customer_id=id)
    print(address)
    return render(request, "accounts/address-list.html", {'address': address})
def addressListManagement(request):
    address = Address.objects.all()
    print(address)
    return render(request, "accounts/address-list.html", {'address': address})

class loginView(views.APIView):
    # authentication_classes = (AllowAny,)
    def post(self, request,format=None):
        data=request.data
        username=data.get('phone_number')
        password=data.get('password')
        print(username,password)
        user=authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                messages.success(request, 'you login successfully.')
                return Response('you login successfully.')
            else:
                return Response(status=status.HTTP_404_NOT_FOUND)
        else:
            return Response(status=status.HTTP_404_NOT_FOUND)


# request.user
# discount = Coupon.objects.all()
# return render(request, "home/discount-list.html", {'discount': discount})


def addressCreate(request):
    if request.method == "POST":
          # this is the added line
        form = addAddressForm(request.POST)
        if form.is_valid():
            print('valid')
            model = form.instance
            form.save(model)
            return redirect('accounts:addressListManagement')
    else:
        form = addAddressForm()
    return render(request, 'accounts/address-create.html', {'form': form})


def update_address(request, id):
    obj = get_object_or_404(Address, id=id)
    form = addAddressForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('accounts:addressListManagement')
    form = addAddressForm()
    return render(request, "accounts/address-update.html", {'form': form})


def profileUpdate(request):
    # context = {}
    obj = get_object_or_404(User, id=request.user.id)
    form = updateUserForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/')
    # context["form"] = form
    form = updateUserForm()

    return render(request, "accounts/profile-update.html", {'obj': obj, 'form': form})


def delete_address(request, id):
    context = {}
    obj = get_object_or_404(Address, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect("accounts:addressListManagement")

    return render(request, "accounts/delete_address.html", context)


def nazer_panel(request):
    list_product = Product.objects.all()
    list_Order = Order.objects.all()
    list_user = User.objects.all()
    list_category = Category.objects.all()
    list_address = Address.objects.all()
    list_discount = Coupon.objects.all()

    return render(request, "accounts/nazer.html", {'product': list_product, 'discount': list_discount,
                                                   'order': list_Order, 'user': list_user,
                                                   'category': list_category, 'address': list_address})





def Operator_user_create(request):
    if request.method == "POST":

        form = User_RegistrationForm(request.POST)
        if form.is_valid():
            print(request.POST.get('is_customer'))
            # print(form.is_customer)
            # print(form.is_admin)
            # print(form.is_operator)
            # print(form.is_nazer)
            request.session['user_registration_info'] = {
                'phone_number': form.cleaned_data['phone'],
                'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'password': form.cleaned_data['password'],
            }
            user_session = request.session['user_registration_info']
            if request.POST.get('is_customer'):
                User.objects.create_customer(user_session['phone_number'], user_session['email'], user_session['full_name'],
                                         user_session['password'])
            elif request.POST.get('is_operator'):
                User.objects.create_operator(user_session['phone_number'], user_session['email'],
                                             user_session['full_name'],
                                             user_session['password'])
            elif request.POST.get('is_nazer'):

accounts/templates/accounts/address-create.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h5>Create New category</h5>
    <form method="POST" >
        {% csrf_token %}

        {{form.as_p}}
{#        {% else %}#}
{#            {% {{ form.customer }}==user.id %}#}
{#        {% endif %}#}
{#        <a type="button" class="btn btn-danger">Cancel</a>#}
{#        <button type="submit" class="btn btn-success">Create</button>#}
{#        <input type="submit" value="Submit" class="btn btn-success">#}
        <input type="submit" value="Submit" class="btn  btn-success"  href="{% url 'accounts:addresscreate' %}">
        <a type="button" class="btn btn-danger" href="{% url 'accounts:addressListManagement' %}">cancle</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/address-list.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>discount List</h4>
    <table class="table">
        <thead>
            <tr>
{#                <th scope="col">category</th>#}
                <th scope="col">city_name</th>
                <th scope="col">avenue_name</th>
                <th scope="col">street_name</th>
                <th scope="col">zipCode</th>
{#                <th scope="col">active</th>#}
{#                <th scope="col">available</th>#}
            </tr>
        </thead>
        <tbody>
            {% for dis in address %}
            <tr>
{#                <td>{{ product.category.name }}</td>#}
                <td>{{ dis.city_name }}</td>
                <td>{{ dis.avenue_name }}</td>
                <td>{{ dis.street_name }}</td>
                <td>{{ dis.zipCode }}</td>
{#                <td>{{ dis.active }}</td>#}
                <td><a type="button" class="btn btn-warning" href="/accounts/addressupdate/{{ dis.id }}">Update</a>
                    <a type="button" class="btn btn-danger" href="/accounts/addressdelete/{{ dis.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% if user.is_customer %}
        <a type="button" class="btn btn-success" href="{% url 'accounts:cusAdd' %}">Create</a>

    {% else %}
        <a type="button" class="btn btn-success" href="{% url 'accounts:addresscreate' %}">Create</a>

{% endif %}
</div>
{% endblock %}

accounts/templates/accounts/delete_address.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="{% url 'accounts:addressListManagement' %}">Cancel </a>
    </form>
</div>
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
{#{% extends 'base.html' %}#}
{% load static %}
<link href="{% static 'css/signin.css' %}" rel="stylesheet">

{% block content %}
<link href="../../static/css/signin.css" rel="stylesheet">

    {#        <script src="../../static/js/script.js"></script>#}

    {#    <form action="" method="post">#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <input type="submit" value="Login">#}
    {#    </form>#}


    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Sign In </h2>
            <a href="{% url 'accounts:user_register' %}">Sign Up </a>

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="{% static 'image/user.jpeg' %}" id="icon" alt="User Icon"/>
            </div>
            <br/>
            <!-- Login Form -->
            <form method="post" action="">
                 {% csrf_token %}
                {{ form.as_p}}
{#                {{ form.phone }}#}
{#                {{ form.password}}#}
{#                      <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">#}
{#                      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">#}
                <input type="submit" value="Login" class="f1" name="login">
            </form>

            <!-- Remind Passowrd -->


        </div>
    </div>




    {#    <div class="container card" id="card">#}
    {#        <div class="front">#}
    {#            <p class="login_word">LOG IN</p>#}
    {#            <img src="../../static/image/male_pic%20(1).png"#}
    {#                 alt="person picture">#}
    {#            <form method="post" action="">#}
    {#                <label>phone </label>#}
    {#                    {% csrf_token %}#}
    {#                {{ form.as_p }}#}
    {#                    <input type="text" name="username" placeholder="phonnumber" class="f1"#}
    {#                       value="{{ form.phone_number }}"    maxlength="10" required >#}
    {##}
    {#                {{ form.password }}#}
    {#                <label>password</label>#}
    {#                <input type="password" name="password" placeholder="password" class="f1" maxlength="10" required#}
    {#                       autocomplete="off"   value="{{ form.phone_number }}" >#}
    {#                <input type="submit" class="f1" name="login" value="log in" />#}
    {#                <p>Not registered? <span onclick="flip()">Create an account</span></p>#}
    {#                 <input type="submit" value="Login" class="f1" name="login" style="background-color: #FFB30E">#}
    {#            </form>#}
    {#        </div>#}
    {##}
    {#    </div>#}
    {#    </form>#}
{% endblock %}
</body>

</html>

accounts/templates/accounts/nazer.html
{% extends "base.html" %}
{% block content %}
    <div class="card-body">

        <div class="card" style="width: 93rem;">
            <div class="card-header">
                user list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in user %}
                    <li class="list-group-item">full_name : {{ u.full_name }} &nbsp;&nbsp; email : {{ u.email }} &nbsp;&nbsp; phone : {{ u.phone_number }} </li>

                {% endfor %}

            </ul>
        </div>
        <div class="card" style="width: 93rem;">
            <div class="card-header">
                order list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in order %}
                    <li class="list-group-item">paid : {{ u.paid }} &nbsp;&nbsp; created : {{ u.created }} &nbsp;&nbsp; sent_status : {{ u.sent_status }} </li>

                {% endfor %}

            </ul>
        </div>
        <div class="card" style="width: 93rem;">
            <div class="card-header">
                product list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in product %}
                    <li class="list-group-item">name : {{ u.name }} &nbsp;&nbsp; available : {{ u.available }} &nbsp;&nbsp; price : {{ u.price }} </li>

                {% endfor %}

            </ul>
        </div>
        <div class="card" style="width: 93rem;">
            <div class="card-header">
                category list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in category %}
                    <li class="list-group-item"> name : {{ u.name }} </li>
                {% endfor %}

            </ul>
        </div>
        <div class="card" style="width: 93rem;">
            <div class="card-header">
                address list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in address %}
                    <li class="list-group-item"> city : {{ u.city }}&nbsp;&nbsp; avenue : {{ u.avenue }}&nbsp;&nbsp; street : {{ u.street }} &nbsp;&nbsp;plate : {{ u.plate }} &nbsp;&nbsp;zipCode : {{ u.zipCode }} </li>
                {% endfor %}

            </ul>
        </div>
        <div class="card" style="width: 93rem;">
            <div class="card-header">
                discount list
            </div>
            <ul class="list-group list-group-flush">
                {% for u in discount %}
                    <li class="list-group-item"> code : {{ u.code }} &nbsp;&nbsp;valid_from : {{ u.valid_from }}&nbsp;&nbsp;valid_to : {{ u.valid_to }}&nbsp;&nbsp;discount : {{ u.discount }}&nbsp;&nbsp;active : {{ u.active }} </li>
                {% endfor %}

            </ul>
        </div>


        {#    <table class="table">#}
        {#        <thead>#}
        {#            <tr>#}
        {#                <th scope="col">category</th>#}
        {#                <th scope="col">city_name</th>#}
        {#                <th scope="col">avenue_name</th>#}
        {#                <th scope="col">street_name</th>#}
        {#                <th scope="col">zipCode</th>#}
        {#                <th scope="col">active</th>#}
        {#                <th scope="col">available</th>#}
        {#            </tr>#}
        {#        </thead>#}
        {#        <tbody>#}
        {#            {% for dis in address %}#}
        {#            <tr>#}
        {#                <td>{{ product.category.name }}</td>#}
        {#                <td>{{ dis.city_name }}</td>#}
        {#                <td>{{ dis.avenue_name }}</td>#}
        {#                <td>{{ dis.street_name }}</td>#}
        {#                <td>{{ dis.zipCode }}</td>#}
        {#                <td>{{ dis.active }}</td>#}
        {#                <td><a type="button" class="btn btn-warning" href="/addressupdate/{{ dis.id }}">Update</a>#}
        {#                    <a type="button" class="btn btn-danger" href="/addressdelete/{{ dis.id }}">Delete</a>#}
        {#                </td>#}
        {#            </tr>#}
        {#            {% endfor %}#}
        {#        </tbody>#}
        {#    </table>#}
        {#    <a type="button" class="btn btn-success" href="{% url 'accounts:addresscreate' %}">Create</a>#}
    </div>
{% endblock %}

accounts/templates/accounts/profile-update.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="main">#}
{#    <!-- Create a Form -->#}
{#    <form method="POST">#}
{#        <!-- Security token by Django -->#}
{#        {% csrf_token %}#}
{##}
{#        <!-- form as paragraph -->#}
{#        {{ form.as_p }}#}
{##}
{#        <input type="submit" value="Update">#}
{#    </form>#}
{##}
{#</div>#}
{#</body>#}
{#</html>#}
{% extends "base.html" %}
{% load static %}
{% block content %}
    {#    <link href="../../static/css/editProfile.css" rel="stylesheet">#}
    {#    <link href="../../static/css/login.css" rel="stylesheet">#}

    <div style="margin-bottom: 20px;margin-top: 50px;background: #fafaff;text-align: center;border: 1px solid #eee; padding: 47px 30px 43px;">
        <div class="card-body" style="margin-top:-5.5%">
            <br/>

            <h4>Update Profile</h4>
            <div class="main">
                <h2>IDENTITY</h2>
                <div class="card">
                    <div class="card-body" style="margin-left: 25%">
                        <ul class="list-group list-group-horizontal">
                            <li class="list-group-item">full_name</li>
                            <li class="list-group-item">{{ obj.full_name }}</li>
                            <li class="list-group-item">Email</li>
                            <li class="list-group-item">{{ obj.email }}</li>
                            <li class="list-group-item">phone_number</li>
                            <li class="list-group-item">{{ obj.phone_number }}</li>
                        </ul>

                    </div>

                </div>


            </div>
        </div>
        <div style="padding:5%;border:1px solid #4f88b7;border-radius:20px;width: 56%;margin-left: 22%">
            {% csrf_token %}
            <form method="post">

                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.full_name }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.phone }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.password }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.email }}
                    </div>
                    <button type="submit" class="btn btn-success">Update</button>
                    <a type="button" class="btn btn-warning" href="/">cancel</a>

                </div>


                {#        <a type="button" class="btn btn-danger" href="{% url 'products:productlist' %}">Cancel</a>#}
            </form>
        </div>

    </div>






{% endblock %}

accounts/templates/accounts/userAddAddress.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="{% url 'accounts:cusAdd' %}">
    {% csrf_token %}
        <div class="mb-3">
            <label for="city_name" class="form-label">city_name</label>
            <input type="text" class="form-control" name="city_name" id="city_name" required>
        </div>
        <div class="mb-3">
            <label for="avenue_name" class="form-label">avenue_name</label>
            <input type="text" name="avenue_name" class="form-control" id="avenue_name" required>
        </div>
        <div class="mb-3">
            <label for="street_name" class="form-label">street_name</label>
            <input type="text" class="form-control" name="street_name" id="street_name" required>
        </div>
        <div class="mb-3">
            <label for="plate" class="form-label">plate</label>
            <input type="text" class="form-control" name="plate" id="plate" required>
        </div>
        <div class="mb-3">
            <label for="zipCode" class="form-label">zipCode</label>
            <input type="text" class="form-control" name="zipCode" id="zipCode" required>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}