accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('loginapi/', views.loginView.as_view(), name='user_login_api'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

    path('addresslist/list/', views.addressList, name='addresslist'),
    path('addressListManagement/list/', views.addressListManagement, name='addressListManagement'),
    path('addresscreate/create/', views.addressCreate, name='addresscreate'),
    path('addressupdate/<int:id>/', views.update_address, name='addressupdate'),
    path('addressdelete/<int:id>/', views.delete_address, name='addressdelete'),
    path('profileUpdate/', views.profileUpdate, name='profileUpdate'),
    path('nazer_panel/', views.nazer_panel, name='nazer_panel'),
    path('usercreate/', views.Operator_user_create, name='usercreate'),
    path('userlist/', views.operator_user_List, name='userlist'),
    path('userupdate/<int:id>/', views.update_Operator_user_, name='userupdate'),
    path('userdelete/<int:id>/', views.delete_user_operator, name='userdelete'),
    path('customer/addAddress', views.customerAddAddress, name='cusAdd'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
    path('', views.OrderView.as_view(), name='OrderView'),  # endpoint
    path('all/', views.showAllOrders),
    path('allOrderItem/', views.showAllOrderItems),
    path('orderView/<int:pk>/', views.show),
    path('orderItemView/<int:pk>/', views.showOrderItemView),
    path('orderHistoryList/history/', views.orderHistoryList,name='orderHistoryList'),
    path('orderStatusList/status/', views.orderStatusList,name='orderHistoryStatusList'),
    path('order_List/list/', views.order_List,name='order_List'),
    path('orderItemcreate/', views.orderItemcreate,name='orderItemcreate'),
    path('orderItemDelete/<int:id>/', views.orderItemDelete,name='orderItemDelete'),
    path('orderItemUpdate/<int:id>/', views.orderItemUpdate,name='orderItemUpdate'),
    # path('getAllProduct/test/', views.getAllProduct,name='getAllProduct'),
]

products/urls.py
from django.urls import path

from . import views
from .api.views import CartItemViews

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='products'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    # path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),

    path('productlist/list/', views.productList, name='productlist'),
    path('productcreate/create/', views.productCreate, name='productcreate'),
    path('productupdate/<int:id>/', views.update_view, name='productupdate'),
    path('productdelete/<int:id>/', views.delete_view, name='productdelete'),

    path('categorylist/list/', views.categoryList, name='categorylist'),
    path('categorycreate/create/', views.categoryCreate, name='categorycreate'),
    path('categoryupdate/<int:id>/', views.update_category, name='categoryupdate'),
    path('categorydelete/<int:id>/', views.delete_category, name='categorydelete'),

    path('discountlist/list/', views.discountList, name='discountlist'),
    path('discountcreate/create/', views.discountCreate, name='discountcreate'),
    path('discountupdate/<int:id>/', views.update_discount, name='discountupdate'),
    path('discountdelete/<int:id>/', views.delete_discount, name='discountdelete'),
    path('cart/cart-items/', CartItemViews.as_view()),
    path('cart/cart-items/<int:id>', CartItemViews.as_view()),



]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav ">
            {% load static %}
            <div class="cart">
                <span class="count">{{ cart|length }}</span>
                <a class="material-icons bi bi-cart" href="{% url 'orders:cart' %}"></a>
            </div>
            {% if request.user.is_authenticated %}
                <a class="nav-link active material-icons bi bi-power" href="{% url 'accounts:user_logout' %}"></a>
                <a class="nav-link active material-icons bi bi-unlock" href="{% url 'products:products' %}">{{ request.user.full_name }}</a>

            {% else %}
                <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
                <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
            {% endif %}
            {% if request.user.is_admin %}
                <ul>
                    <li class="nav-item dropdown">
                        <a style="color:white" class="nav-link dropdown-toggle  material-icons bi bi-file-earmark-richtext" href="#"
                           id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="nav-link active" href="{% url 'products:productlist' %}" style="color:black">product
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'products:discountlist' %}" style="color:black">discount
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'accounts:userlist' %}" style="color:black">user
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'orders:order_List' %}" style="color:black">order
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'accounts:addressListManagement' %}"
                                   style="color:black">adress
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'products:categorylist' %}" style="color:black">category
                                management</a>
                            </li>
                            <li><a class="nav-link active" href="{% url 'accounts:profileUpdate' %}"
                                   style="color:black">profile update</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
            {% if request.user.is_customer %}

                <a class="nav-link active material-icons bi bi-file-person"
                   href="{% url 'accounts:profileUpdate' %}">profile</a>
                <a class="nav-link active material-icons bi bi-building"
                   href="{% url 'accounts:addresslist' %}">address</a>
                <a class="nav-link active material-icons bi bi-file-text"
                   href="{% url 'orders:orderHistoryList' %}">order
                    history</a>
                <a class="nav-link active material-icons bi bi-clipboard-check"
                   href="{% url 'orders:orderHistoryStatusList' %}">order status</a>
            {% endif %}
            {% if request.user.is_nazer %}
                <i class="bi-card-heading"></i>
                <a class="nav-link active material-icons bi bi-card-heading"
                   href="{% url 'accounts:nazer_panel' %}">nazer
                    panel</a>
                <a class="nav-link active material-icons bi bi-file-person"
                   href="{% url 'accounts:profileUpdate' %}">profile
                    update</a>
            {% endif %}
            {% if request.user.is_operator %}
                <ul>
                    <li class="nav-item dropdown">
                        <a style="color:white"
                           class="nav-link dropdown-toggle material-icons bi bi-file-earmark-richtext" href="#"
                           id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            management
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a style="color:black" class="nav-link active" href="{% url 'accounts:userlist' %}">user
                                management</a>
                            </li>
                            <li><a style="color:black" class="nav-link active" href="{% url 'orders:order_List' %}">order
                                management</a>
                            </li>
                            <li><a style="color:black" class="nav-link active"
                                   href="{% url 'accounts:addressListManagement' %}">adress management</a></li>
                            <li><a style="color:black" class="nav-link active "
                                   href="{% url 'accounts:profileUpdate' %}">profile
                                update</a></li>
                        </ul>
                    </li>
                </ul>


                {#                <a class="nav-link active">operater</a>#}


            {% endif %}
        </div>
    </div>
</nav>